services:
  backend:
    image: ghcr.io/marl0nx/glidedot-backend:latest
    container_name: glide-backend
    ports:
      - "3001:3001"
    volumes:
      - glide_data:/app/data
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DB_URL=data/db.sqlite
      # Encryption Key for Secrets (Tokens, API Keys).
      - DB_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      # S3 Backups (Optional)
      - S3_ENDPOINT=
      - S3_REGION=us-east-1
      - S3_BUCKET=
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
    restart: unless-stopped

  frontend:
    image: ghcr.io/marl0nx/glidedot-frontend:latest
    container_name: glide-frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
      # Base URL to the backend API (must be accessible from the user's browser)
      - NUXT_PUBLIC_API_BASE=https://api.your-domain.com/v1
      # OIDC Configuration
      - NUXT_PUBLIC_OIDC_ENABLED=false
      - NUXT_OIDC_PROVIDERS_OIDC_CLIENT_ID=
      - NUXT_OIDC_PROVIDERS_OIDC_CLIENT_SECRET=
      - NUXT_OIDC_PROVIDERS_OIDC_AUTHORIZATION_URL=
      - NUXT_OIDC_PROVIDERS_OIDC_TOKEN_URL=
      - NUXT_OIDC_PROVIDERS_OIDC_REDIRECT_URI=
      - NUXT_OIDC_PROVIDERS_OIDC_USER_INFO_URL=
      # OIDC Secrets
      - NUXT_OIDC_SESSION_SECRET=supersecret_session_key
      - NUXT_OIDC_TOKEN_KEY=
      - NUXT_OIDC_AUTH_SESSION_SECRET=supersecret_auth_key
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  glide_data:
